services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:16
    container_name: labase-service-db
    restart: always
    environment:
      POSTGRES_DB: labase-service
      POSTGRES_USER: labase
      POSTGRES_PASSWORD: labase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
